version: '3.8'
services:
  # 第三方软件
  MySQL:
    container_name: MySQL
    image: mysql:8.0
    build:
      context: ./mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
               'mysqld',
                # innodb-buffer-poll-size： InnoDBBufferPoll是InnoDB用户缓存它的数据和索引的内存缓冲区，常见做法为这个值大于热点数据，如果不清楚环境的数据量和访问模式，建议设置为机器物理内存的70%~80%
               '-innodb-buffer-poll-size=13G',
               # 日志组里每个日志文件的大小。默认5MB。值越大，在缓冲池中需要检查点刷新的行为就越少，因此也越节约磁盘I/O，但更大的日志文件也意味着在崩溃时恢复的更慢，建议设置为256MB或更大
               '-innodb_log_file_size=256MB'
               # 默认值1，当设置2时，在每个事务提交时， 日志缓冲被写到文件中，但不对日志文件做刷新到磁盘的操作
               '--innodb_flush_log_at_trx_commit=2',
               '--character-set-server=utf8mb4',
               '-collation-server=utf8mb4_unicode_ci',
               '--default-time-zone=+8:00',
               '--lower-case-table-names=1'
    ]
    environment:
      mysql-database: 'sun-cloud'
      mysql_root_password: 1111

  Redis:
    container_name: Redis
    image: redis
    build:
      context: ./redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/conf/redis.conf:/home/software/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/software/redis/redis.conf

  Nginx:
    container_name: Nginx
    image: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/html/dish:/home/sun/projects/sun-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d

  Nacos:
    container_name: nacos
    image: nacos/nacos-server
    build:
      context: ./nacos
    environment:
      - MODE=standlone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    restart: always
    ports:
      - '8848:8848'
      - '9848:9848'
      - '9849:9849'

  # 项目
  SUN-Gateway:
    container_name: sun-gateway
    restart: always
    build:
      context: ./sun-infrastructure/sun-gateway
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    depends_on:
      - Redis
      - MySQL



