server:
  port: 9002
  servlet:
    context-path: /manager

spring:
  application:
    name: sun-manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///sun-cloud?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&
    username: root
    password: 1111
    hikari:
      minimum-idle: 9
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 6000000
      connection-test-query: SELECT 1
      max-lifetime: 120000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.sixsixsix516.manager.model
  configuration:
    map-underscore-to-camel-case: true